[env:esp32s3]
platform          = espressif32
board             = esp32s3box
framework         = arduino

; Waveshare ESP32-S3-Touch-AMOLED-1.75 hardware settings
board_build.mcu         = esp32s3
board_build.f_cpu       = 240000000L
board_build.flash_mode  = qio
board_build.flash_size  = 16MB
board_build.psram_type  = opi

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    lovyan03/LovyanGFX @ ^1.1
    links2004/WebSockets @ ^2.3.6
    bblanchon/ArduinoJson @ ^7

upload_port      = /dev/cu.usbmodem1101
monitor_port     = /dev/cu.usbmodem1101
monitor_speed    = 115200
upload_speed     = 921600
